### ISSUE TITLE
Training issue at epoch 10

### ISSUE THREAD

**Issue by ellamcpher** [funalab/QCANet#7]
Hi! 

I am running the QCANet in google colab with python version 3.6.9, chainer 7.4.0, and numpy 1.19.4, and I keep getting an error during training at epoch 10, meaning I cannot train for more than 9 epochs. 
For example when I run the example data:

`!python src/tools/train.py --conf_file confs/example_train_nsn.cfg --gpu_id 0 `

I get the following:

```
Output Directory not exist! Create...
Output Directory: ./results/result_train_nsn_Jan8Fri_2021_121356

============================
[Dataset]
root_path = example_datasets
input_format = tif
image_dtype = uint16
resolution = (1.0, 1.0, 2.18)
split_list_train = example_datasets/split_list/train.txt
split_list_validation = example_datasets/split_list/validation.txt

[Model]
model = NSN
ndim = 3
lossfun = F.softmax_cross_entropy
ch_in = 1
ch_base = 16
ch_out = 2

[Runtime]
save_dir = results/result_train_nsn
batchsize = 1
val_batchsize = 1
epoch = 150
optimizer = Adam
init_lr = 0.002
weight_decay = 0.0001
gpu = 0
patch_size = (128, 128, 128)
padding_size = (128, 128, 128)
normalization = 0
augmentation = 0
class_weight = (1, 1)
scaling = 1

============================

Loading datasets...
-- train_dataset.size = 1
-- validation_dataset.size = 1
Initializing models...
[epoch 1]
train mean loss=0.8914775848388672
train accuracy=0.24427080154418945, train recall=0.9315464210451543
train precision=0.02426526370325597, specificity=0.23014581110009688
train F-measure=0.04729847922801842, IoU=0.024222073227719628
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 2]
train mean loss=0.6999218463897705
train accuracy=0.6951837539672852, train recall=0.9927261670876603
train precision=0.062292700108603126, specificity=0.6889913142354249
train F-measure=0.11722936023067489, IoU=0.0622642810305549
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 3]
train mean loss=0.6320231556892395
train accuracy=0.9102859497070312, train recall=0.9946427746732555
train precision=0.18647883421506065, specificity=0.9085072590642141
train F-measure=0.31407405246963094, IoU=0.18629172469271424
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 4]
train mean loss=0.5670128464698792
train accuracy=0.9520506858825684, train recall=0.9911039491401956
train precision=0.3095303753136806, specificity=0.9511884634897954
train F-measure=0.4717340940253108, IoU=0.3086727853975456
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 5]
train mean loss=0.5068442821502686
train accuracy=0.9686098098754883, train recall=0.9896025332010019
train precision=0.3904053398963344, specificity=0.9681774780833877
train F-measure=0.5599187089700909, IoU=0.38881048761466186
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 6]
train mean loss=0.45387524366378784
train accuracy=0.9755411148071289, train recall=0.9658677256181156
train precision=0.4504585942322956, specificity=0.9757402744536574
train F-measure=0.6143830158324437, IoU=0.4434003211944963
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 7]
train mean loss=0.407667875289917
train accuracy=0.9791359901428223, train recall=0.9822888283378747
train precision=0.49737509792229356, specificity=0.9790695115407874
train F-measure=0.6603742829865019, IoU=0.49295431895612674
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 8]
train mean loss=0.381524920463562
train accuracy=0.9798483848571777, train recall=0.9653973184015399
train precision=0.5203853046594982, specificity=0.980170446707253
train F-measure=0.6762477496456888, IoU=0.5108567327947406
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 9]
train mean loss=0.35268935561180115
train accuracy=0.9843149185180664, train recall=0.9789622976007564
train precision=0.564091039104319, specificity=0.9844251177824919
train F-measure=0.7157547267636791, IoU=0.5573349123255595
test mean loss=0.0
test accuracy=0, recall=0
test precision=0, specificity=0
test F-measure=0, IoU=0
[epoch 10]
Traceback (most recent call last):
  File "src/tools/train.py", line 145, in <module>
    main()
  File "src/tools/train.py", line 135, in main
    train_eval, test_eval, best_score = trainer.training((train_iterator, validation_iterator))
  File "/content/drive/My Drive/QCANet/src/lib/trainer.py", line 86, in training
    teseval, test_sum_loss = self._validater(val_iter, epoch=epoch)
  File "/content/drive/My Drive/QCANet/src/lib/trainer.py", line 262, in _validater
    pre_img = np.zeros(pad_size)
TypeError: 'float' object cannot be interpreted as an integer
```

If I change the trainer.py code so pad_size, sh, and stride are all integers, I then get this error:

```
[epoch 10]
Traceback (most recent call last):
  File "src/tools/train.py", line 145, in <module>
    main()
  File "src/tools/train.py", line 135, in main
    train_eval, test_eval, best_score = trainer.training((train_iterator, validation_iterator))
  File "/content/drive/My Drive/QCANet/src/lib/trainer.py", line 86, in training
    teseval, test_sum_loss = self._validater(val_iter, epoch=epoch)
  File "/content/drive/My Drive/QCANet/src/lib/trainer.py", line 303, in _validater
    pre_img[z:z+stride[0], y:y+stride[1], x:x+stride[2]] += pred[sh[0]:-sh[0], sh[1]:-sh[1], sh[2]:-sh[2]]
ValueError: operands could not be broadcast together with shapes (64,64,64) (64,64,28) (64,64,64) 
```

Have others successfully ran QCANet on colab? Any ideas of why it can only run 9 epochs?

Thank you!
Ella

**Comment by tokkuman** [comment]
@ellamcpher 

Sorry for the late reply.
I checked the code and found that when I migrated the code of QCANet from python 2.7 to 3.6, there was still a bug in the evaluation phase.

The fixed code has been pushed.  (commit hash: `062fd2a`)
I have confirmed that QCANet correctly works even after 10 epochs on google colab.
Thank you for reporting the error!

Best,
Yuta

**Comment by ellamcpher** [comment]
Thank you!!
